apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-ci-pipeline
spec:

  params:
    - name: repo-url
      type: string
    - name: git-revision
      type: string
    - name: image-tag
      type: string
    - name: severity
      type: string

  workspaces:
    - name: shared-workspace

  tasks:

    - name: validate-params
      taskRef:
        name: validate-params-task
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: image-tag
          value: $(params.image-tag)
        - name: severity
          value: $(params.severity)

    - name: clone-repo
      runAfter:
        - validate-params
      taskRef:
        name: git-clone-task
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: git-revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-build
      runAfter:
        - clone-repo
      taskRef:
        name: maven-build-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: unit-test
      runAfter:
        - maven-build
      taskRef:
        name: unit-test-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: sonar-scan
      runAfter:
        - unit-test
      taskRef:
        name: sonar-scan-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: trivy-fs-scan
      runAfter:
        - sonar-scan
      taskRef:
        name: trivy-fs-scan-task
      params:
        - name: severity
          value: $(params.severity)
      workspaces:
        - name: source
          workspace: shared-workspace