apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: java-ci-run
spec:
  pipelineRef:
    name: java-ci-pipeline

  params:
    - name: repo-url
      value: https://github.com/Perumal05/Java-tekton-test-app.git

    - name: git-revision
      value: main

    - name: image-tag
      value: v1

    - name: severity
      value: "CRITICAL"

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi