apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: java-ci-binding
spec:
  params:
    - name: git-revision
      value: $(body.ref)
    - name: repo-url
      value: $(body.repository.clone_url)

      