apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build-task
spec:
  workspaces:
    - name: source

  steps:
    - name: maven-build
      image: maven:3.9-eclipse-temurin-21
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        set -e

        echo "Starting Maven build..."

        mvn clean package -DskipTests -B

        echo "Maven build completed."
        
    - name: verify-target-folder
      image: busybox
      workingDir: /workspace/source
      script: |
        echo "Checking target folder..."
        ls -l target