apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: unit-test-task
spec:
  workspaces:
    - name: source

  steps:
    - name: run-tests
      image: maven:3.9-eclipse-temurin-21
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        set -e

        echo "Running unit tests..."

        mvn test -B

        echo "Unit tests completed."